[package]
name = "food-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = { version = "0.21.0", default-features = false, features = ["serde-json"] }
oxhttp = "0.2.7"
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
jiff = "0.1.25"
